### ISSUE TITLE
I have a question about the description of Example in README.md.

### ISSUE THREAD

**Issue by nyubachi** [SikSo1897/hmctdm#1]
Thank you for developing a great application.

I'm having trouble installing hmctdm, so I've contacted you.

First, when I follow the instructions, the package `hmctdmr` is installed instead of `hmctdm`.
Is this correct?
I am also concerned that in the README.md Example, it says `library(hmctdm)`.

Also, in README.md, it says `hmctdmr::get_sample_data(drug="amikacin")`.
But it seems that there is no function called `get_sample_data()` in the `hmctdmr` package.

The above may be a misunderstanding caused by my ignorance.
If so, I apologize.

Please let me know if there is a way to solve this problem.

**Comment by shanmdphd** [comment]
I also recognized the first issue. It would be better if you can specify the exact package title.
